### ISSUE TITLE
It is both TX and RX communication mixed up

### ISSUE THREAD

**Issue by ngsmg** [dalathegreat/Nissan-Leaf-BatteryPairing#1]
It is clearly both the messages sent by a diagnostic device, and the responses received from the car mixed up and all marked as TX. I would at least filter out the car's response messages from it, from addresses 7bb, 79a, 763, 78c, 793, 70f, 72d, 72e.

**Comment by dalathegreat** [comment]
Well spotted, I've uploaded a new file, "BatteryPairingZE0CommandsMinusResponseMessages.log", I'll update the readme also!

**Comment by ngsmg** [comment]
Quick fix! Unluckily I cannot test it, because I'm not into changing any leaf batteries soon. Btw you also have the VIN number in the un"censored" version (lines 45-50), if that raises any privacy concerns I suggest you remove those lines.
